## makefile automates the build and deployment for lein projects

# edit these if you want
#USER=		johndoe
#APP_SCR_NAME=	${project.app.name}
#PROJ=		
#REMOTE=	origin
#DIST_PREFIX=	$(HOME)/Desktop

# location of the http://github.com/plandes/clj-zenbuild cloned directory
ZBHOME=		../clj-zenbuild

all:		info

include $(ZBHOME)/src/mk/compile.mk
