project:
  artifacts: ['*.conf', '*.json', '*.yml']
pixi:
  project:
    channels: ['conda-forge']
    platforms: ['osx-arm64', 'linux-64', 'win-64']
build:
  project_dir: .
  template_dir: zenbuild/src/relpo/template
  change_log_file_name: CHANGELOG.md
